##  -*-  coding: utf-8; mode: ruby -*-  ##
##  vi: set ft=ruby

load  File.expand_path("DetectOS.rb")  if File.exists?("DetectOS.rb")

Vagrant.configure("2") do |config|
  config.vm.box = "takahiro-itou/ubuntu-focal64-libreoffice"

  config.vm.provider "virtualbox" do |v|
    v.name   = "vagrant-ubuntu-libreoffice"
    v.memory = "3072"

    v.gui    = false
    v.customize [
      "modifyvm",           :id,
      "--cableconnected1",  "on",
      "--hwvirtex",         "on",
      "--nestedpaging",     "on",
      "--largepages",       "on",
      "--ioapic",           "on",
      "--pae",              "on",
      "--paravirtprovider", "kvm",
    ]

    #
    # ディスクを追加する
    #
    disk_file = './disk/ubuntu-libreoffice-sdb.vdi'
    unless File.exists?(disk_file)
        v.customize [
            'createmedium',     "disk",
            '--filename',       disk_file,
            '--size',           50 * 1024,
            '--format',         'VDI',
        ]
    end
    v.customize [
        'storageattach',    :id,
        '--storagectl',     'SCSI',
        '--port',           2,
        '--device',         0,
        '--type',           'hdd',
        '--medium',         disk_file,
    ]

  end

  config.vm.boot_timeout = 900
  config.vm.network("private_network", ip: "192.168.33.13")

  config.vm.provision("file",
                      source: "../data/",
                      destination: "/tmp/")

    config.vm.provision("file",
                        source: "~/VagrantConfig/",
                        destination: "/tmp/")

  config.vm.provision("root", type: "shell",
                      path: "provision.root.sh",
                      privileged: true)
  config.vm.provision("user", type: "shell",
                      path: "provision.user.sh",
                      privileged: false)
  config.vm.provision("hguser", type: "shell",
                      path: "provision.hguser.sh",
                      privileged: false)
  config.vm.synced_folder(".", "/vagrant", disabled: true)

end
