##  -*-  coding: utf-8; mode: ruby -*-  ##
##  vi: set ft=ruby

Vagrant.configure("2") do |config|
  config.vm.box = "takahiro-itou/ubuntu-jammy64-libreoffice"

  config.vm.provider "virtualbox" do |v|
    v.name   = "vagrant-ubuntu-libreoffice"
    v.cpus   = 4
    v.memory = "8192"
    v.gui    = false
  end

  config.vm.network(:forwarded_port, guest: 22, host: 11322, id: "ssh")
  config.vm.network("private_network", ip: "192.168.33.13")

  config.vm.provision("root", type: "shell",
                      path: "provision.root.sh",
                      privileged: true)
  config.vm.provision("user", type: "shell",
                      path: "provision.user.sh",
                      privileged: false)
  config.vm.provision("hguser", type: "shell",
                      path: "provision.hguser.sh",
                      privileged: false)
  config.vm.synced_folder(".", "/vagrant", disabled: true)
end

load  File.expand_path('common/CommonCustomize.rb')

$disk_image_file = File.expand_path('./disk/ubuntu-libreoffice-sdc.vdi')
load  File.expand_path('common/AttachSCSIHdd.rb')

# Provisioning(s)
load  File.expand_path('common/UploadFiles.rb')
